//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Questionnaire.Serialization.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Questionnaire.Serialization.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        /// pages: [
        ///  {
        ///   elements: [
        ///    {
        ///     $type: &quot;rating&quot;,
        ///     name: &quot;question1&quot;
        ///    },
        ///    {
        ///     $type: &quot;matrix&quot;,
        ///     name: &quot;question2&quot;,
        ///     columns: [
        ///      &quot;Column 1&quot;,
        ///      &quot;Column 2&quot;,
        ///      &quot;Column 3&quot;
        ///     ],
        ///     rows: [
        ///      &quot;Row 1&quot;,
        ///      &quot;Row 2&quot;
        ///     ]
        ///    },
        ///    {
        ///     $type: &quot;matrixdropdown&quot;,
        ///     choices: [
        ///      1,
        ///      2,
        ///      3,
        ///      4,
        ///      5
        ///     ],
        ///     columns: [
        ///      {
        ///       name: &quot;Column 1&quot;,
        ///       choices: [
        ///        {
        ///         value: &quot;1&quot;,
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string complexSurveyJson {
            get {
                return ResourceManager.GetString("complexSurveyJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        /// pages: [
        ///  {
        ///   elements: [
        ///    {
        ///     $type: &quot;rating&quot;,
        ///     name: &quot;question1&quot;
        ///    },
        ///    {
        ///     $type: &quot;matrix&quot;,
        ///     name: &quot;question2&quot;,
        ///     columns: [
        ///      &quot;Column 1&quot;,
        ///      &quot;Column 2&quot;,
        ///      &quot;Column 3&quot;
        ///     ],
        ///     rows: [
        ///      &quot;Row 1&quot;,
        ///      &quot;Row 2&quot;
        ///     ]
        ///    },
        ///    {
        ///     $type: &quot;matrixdropdown&quot;,
        ///     choices: [
        ///      1,
        ///      2,
        ///      3,
        ///      4,
        ///      5
        ///     ],
        ///     columns: [
        ///      {
        ///       name: &quot;Column 1&quot;,
        ///       choices: [
        ///        {
        ///         value: &quot;1&quot;,
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string complexSurveyNoNesting {
            get {
                return ResourceManager.GetString("complexSurveyNoNesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        /// pages: [
        ///  {
        ///   elements: [
        ///    {
        ///     $type: &quot;rating&quot;,
        ///     name: &quot;question1&quot;
        ///    },
        ///    {
        ///     $type: &quot;matrix&quot;,
        ///     name: &quot;question2&quot;,
        ///     columns: [
        ///      &quot;Column 1&quot;,
        ///      &quot;Column 2&quot;,
        ///      &quot;Column 3&quot;
        ///     ],
        ///     rows: [
        ///      &quot;Row 1&quot;,
        ///      &quot;Row 2&quot;
        ///     ]
        ///    },
        ///    {
        ///     $type: &quot;matrixdropdown&quot;,
        ///     name: &quot;question3&quot;,
        ///     columns: [
        ///      {
        ///       name: &quot;Column 1&quot;,
        ///       choices: [
        ///        {
        ///         value: &quot;1&quot;,
        ///         text: &quot;A&quot;
        ///        },
        ///        {
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string surveyJson {
            get {
                return ResourceManager.GetString("surveyJson", resourceCulture);
            }
        }
    }
}
