//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Questionnaire.DataBroker
{
    using System;
    
    public enum EAnswerType : int
    {
        Textual = 0,
        Numeric = 1,
        NumericRange = 2,
        Boolean = 3
    }
}
