//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Questionnaire.DataBroker
{
    using System;
    
    public enum EAppearanceType : int
    {
        VerticalList = 0,
        HorizontalList = 1,
        HorizontalListInline = 2,
        DropDown = 3
    }
}
