//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Questionnaire.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatrixRowTemplate : ValueTextPair
    {
        public Nullable<int> MatrixQuestionTemplateId { get; set; }
        public Nullable<int> MatrixDropdownQuestionTemplateId { get; set; }
    
        public virtual MatrixQuestionTemplate MatrixQuestion { get; set; }
        public virtual MatrixDropdownQuestionTemplate MatrixDropdownQuestion { get; set; }
    }
}
