//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Questionnaire.Data
{
    using System;
    using System.Collections.Generic;
    
    public abstract partial class QuestionTemplateBase
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public int SurveyId { get; set; }
    
        public virtual Survey Survey { get; set; }
    }
}
