//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Questionnaire.DataBroker
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuestionnaireModelContainer : DbContext
    {
        public QuestionnaireModelContainer()
            : base("name=QuestionnaireModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<QuestionTemplate> QuestionTemplates { get; set; }
        public virtual DbSet<AnswerTemplate> AnswerTemplates { get; set; }
        public virtual DbSet<Poll> Polls { get; set; }
        public virtual DbSet<VotingSession> VotingSessions { get; set; }
        public virtual DbSet<SessionResult> SessionResults { get; set; }
        public virtual DbSet<Localization> Localizations { get; set; }
        public virtual DbSet<SurveySection> SurveySections { get; set; }
    }
}
