//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Questionnaire.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SelectQuestionTemplateBase : QuestionTemplateBase
    {
        public string CommentText { get; set; }
        public string OtherText { get; set; }
        public string OtherErrorText { get; set; }
    }
}
