//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Questionnaire.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveySection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SurveySection()
        {
            this.QuestionTemplates = new HashSet<QuestionTemplate>();
        }
    
        public int Id { get; set; }
        public int DisplayOrder { get; set; }
        public string Description { get; set; }
        public int PollId { get; set; }
    
        public virtual Poll Poll { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuestionTemplate> QuestionTemplates { get; set; }
    }
}
