//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Questionnaire.DataBroker
{
    using System;
    using System.Collections.Generic;
    
    public partial class VotingSession
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VotingSession()
        {
            this.SessionResults = new HashSet<SessionResult>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public VotingSessionState State { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public System.DateTime Date { get; set; }
        public int PollId { get; set; }
    
        public virtual Poll Poll { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SessionResult> SessionResults { get; set; }
    }
}
