//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PollQuestionnaire.UI.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PollQuestionnaire.UI.Web.Resources.LocalizedResources", typeof(LocalizedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get help with this Survey.
        /// </summary>
        public static string helpEmailLink {
            get {
                return ResourceManager.GetString("helpEmailLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string patque_btnPrint_Text {
            get {
                return ResourceManager.GetString("patque_btnPrint_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print PDF version of this form.
        /// </summary>
        public static string patque_btnPrint_tooltip {
            get {
                return ResourceManager.GetString("patque_btnPrint_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset survey.
        /// </summary>
        public static string patque_btnReset_text {
            get {
                return ResourceManager.GetString("patque_btnReset_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete current progress, and start survey again.
        /// </summary>
        public static string patque_btnReset_tooltip {
            get {
                return ResourceManager.GetString("patque_btnReset_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string patque_dialog_btnNo_caption {
            get {
                return ResourceManager.GetString("patque_dialog_btnNo_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string patque_dialog_btnOk_caption {
            get {
                return ResourceManager.GetString("patque_dialog_btnOk_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string patque_dialog_btnYes_caption {
            get {
                return ResourceManager.GetString("patque_dialog_btnYes_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the link to copy it to your clipboard.
        /// </summary>
        public static string patque_dialog_clickForClipboard {
            get {
                return ResourceManager.GetString("patque_dialog_clickForClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue survey later.
        /// </summary>
        public static string patque_dialog_continueLaterText {
            get {
                return ResourceManager.GetString("patque_dialog_continueLaterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can continue the survey at any time anywhere.
        /// </summary>
        public static string patque_dialog_continueLaterTitle {
            get {
                return ResourceManager.GetString("patque_dialog_continueLaterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Well... That wasn\&apos;t that well....
        /// </summary>
        public static string patque_dialog_error_caption {
            get {
                return ResourceManager.GetString("patque_dialog_error_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due to &quot;temporary difficulties&quot; we were unable to verify the very existence of the file you requested. Sorry about that, and give it a try in a few minutes....
        /// </summary>
        public static string patque_dialog_error_errorVerifyingPdfExistence {
            get {
                return ResourceManager.GetString("patque_dialog_error_errorVerifyingPdfExistence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s hard to believe but the file was here just a moment ago :-) Weeeell... not realy... The truth is - we don&apos;t have it... Sorry....
        /// </summary>
        public static string patque_dialog_error_pdfNotFound {
            get {
                return ResourceManager.GetString("patque_dialog_error_pdfNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are experiencing &quot;temporary&quot; dificulties :-) However data you submitted is stored in your browser. Please try to submit your data whenever you feel like it....
        /// </summary>
        public static string patque_dialog_error_saveSessionFailed {
            get {
                return ResourceManager.GetString("patque_dialog_error_saveSessionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We were unable to find your session data. Please check the session code and try again....
        /// </summary>
        public static string patque_dialog_error_sessionNotFound {
            get {
                return ResourceManager.GetString("patque_dialog_error_sessionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We were unable to load the survey. Have you checked the survey code?.
        /// </summary>
        public static string patque_dialog_error_surveyLoadFailed {
            get {
                return ResourceManager.GetString("patque_dialog_error_surveyLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you proceed all of your session data will be lost. Please consider saving your changes before reseting survey. Do you want to reset current progress?.
        /// </summary>
        public static string patque_dialog_resetWarningText {
            get {
                return ResourceManager.GetString("patque_dialog_resetWarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your data will be lost.
        /// </summary>
        public static string patque_dialog_resetWarningTitle {
            get {
                return ResourceManager.GetString("patque_dialog_resetWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string patque_dialog_resume_btnClose {
            get {
                return ResourceManager.GetString("patque_dialog_resume_btnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send email and Close.
        /// </summary>
        public static string patque_dialog_resume_btnSendEmail {
            get {
                return ResourceManager.GetString("patque_dialog_resume_btnSendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Please enter valid email.
        /// </summary>
        public static string patque_dialog_resume_emailWarning {
            get {
                return ResourceManager.GetString("patque_dialog_resume_emailWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will be able to resume this survey any time you like. To do so, you will need the link cited below..
        /// </summary>
        public static string patque_dialog_resume_text1 {
            get {
                return ResourceManager.GetString("patque_dialog_resume_text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can simply write it down, or if you want us to email it to you, please leave your email address in the box under the link. Rest assured your email address will not be used in any other purposes..
        /// </summary>
        public static string patque_dialog_resume_text2 {
            get {
                return ResourceManager.GetString("patque_dialog_resume_text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the link to add it to your clipboard, or simply write it down..
        /// </summary>
        public static string patque_dialog_resume_text2_noEmail {
            get {
                return ResourceManager.GetString("patque_dialog_resume_text2_noEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your work is saved.
        /// </summary>
        public static string patque_dialog_resume_title {
            get {
                return ResourceManager.GetString("patque_dialog_resume_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported Languages.
        /// </summary>
        public static string patque_dialog_supportedLanguagesCaption {
            get {
                return ResourceManager.GetString("patque_dialog_supportedLanguagesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you!.
        /// </summary>
        public static string patque_dialog_thankYouCaption {
            get {
                return ResourceManager.GetString("patque_dialog_thankYouCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We don&apos;t have any survey available for you at this moment....
        /// </summary>
        public static string patque_noSurvey {
            get {
                return ResourceManager.GetString("patque_noSurvey", resourceCulture);
            }
        }
    }
}
