// <auto-generated />
namespace Questionnaire.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Rev004 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Rev004));
        
        string IMigrationMetadata.Id
        {
            get { return "201705281940046_Rev004"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
